# Sakura Shim System
# Creates executable wrappers for PATH integration

function New-SakuraShim {
    param(
        [string]$AppName,
        [string]$BinPath,
        [string]$ShimName
    )

    $shimPath = Join-Path $Script:SakuraShims "$ShimName.cmd"

    # Create CMD shim (most compatible on Windows)
    $shimContent = @"
@echo off
REM Sakura shim for $AppName
REM Generated by Sakura Package Manager
"$BinPath" %*
"@

    Set-Content -Path $shimPath -Value $shimContent -Encoding ASCII
    Write-SakuraSuccess "Created shim: $ShimName"
}

function Remove-SakuraShim {
    param([string]$ShimName)

    $shimPath = Join-Path $Script:SakuraShims "$ShimName.cmd"
    if (Test-Path $shimPath) {
        Remove-Item -Path $shimPath -Force
        Write-SakuraSuccess "Removed shim: $ShimName"
    }
}

function New-SakuraShortcut {
    param(
        [string]$AppName,
        [string]$ExecutablePath,
        [string]$Label
    )

    $startMenu = [Environment]::GetFolderPath("StartMenu")
    $programsDir = Join-Path $startMenu "Programs\Sakura"
    if (-not (Test-Path $programsDir)) {
        New-Item -ItemType Directory -Path $programsDir -Force | Out-Null
    }

    $shortcutPath = Join-Path $programsDir "$Label.lnk"
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $ExecutablePath
    $shortcut.WorkingDirectory = Split-Path -Parent $ExecutablePath
    $shortcut.Description = "$Label (via Sakura)"
    $shortcut.Save()

    Write-SakuraSuccess "Created shortcut: $Label"
}

function Remove-SakuraShortcuts {
    param([string]$AppName)

    $startMenu = [Environment]::GetFolderPath("StartMenu")
    $programsDir = Join-Path $startMenu "Programs\Sakura"

    if (Test-Path $programsDir) {
        $shortcuts = Get-ChildItem -Path $programsDir -Filter "*.lnk" -ErrorAction SilentlyContinue
        foreach ($shortcut in $shortcuts) {
            $shell = New-Object -ComObject WScript.Shell
            $lnk = $shell.CreateShortcut($shortcut.FullName)
            if ($lnk.TargetPath -like "*$AppName*") {
                Remove-Item -Path $shortcut.FullName -Force
            }
        }
    }
}

function Reset-SakuraShims {
    $shims = Get-ChildItem -Path $Script:SakuraShims -Filter "*.cmd" -ErrorAction SilentlyContinue
    foreach ($shim in $shims) {
        Remove-Item -Path $shim.FullName -Force
    }

    # Rebuild from installed apps
    $apps = Get-ChildItem -Path $Script:SakuraApps -Directory -ErrorAction SilentlyContinue
    foreach ($app in $apps) {
        $manifest = Get-InstalledManifest -AppName $app.Name
        if ($manifest -and $manifest.bin) {
            $currentDir = Join-Path $app.FullName "current"
            $bins = if ($manifest.bin -is [array]) { $manifest.bin } else { @($manifest.bin) }
            foreach ($bin in $bins) {
                $binPath = Join-Path $currentDir $bin
                if (Test-Path $binPath) {
                    New-SakuraShim -AppName $app.Name -BinPath $binPath -ShimName ([System.IO.Path]::GetFileNameWithoutExtension($bin))
                }
            }
        }
    }
}
